// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc-gateway/proto/gateway.proto

package grpc_gateway // import "github.com/lpy-neo/micro-framework-test/grpc-gateway/grpc_gateway"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import comm_proto "github.com/lpy-neo/micro-framework-test/comm_proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcServiceClient is the client API for GrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcServiceClient interface {
	GrpcReq(ctx context.Context, in *comm_proto.GrpcRequest, opts ...grpc.CallOption) (*comm_proto.GrpcReply, error)
	GrpcStream(ctx context.Context, opts ...grpc.CallOption) (GrpcService_GrpcStreamClient, error)
}

type grpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewGrpcServiceClient(cc *grpc.ClientConn) GrpcServiceClient {
	return &grpcServiceClient{cc}
}

func (c *grpcServiceClient) GrpcReq(ctx context.Context, in *comm_proto.GrpcRequest, opts ...grpc.CallOption) (*comm_proto.GrpcReply, error) {
	out := new(comm_proto.GrpcReply)
	err := c.cc.Invoke(ctx, "/grpc_gateway.GrpcService/GrpcReq", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcServiceClient) GrpcStream(ctx context.Context, opts ...grpc.CallOption) (GrpcService_GrpcStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GrpcService_serviceDesc.Streams[0], "/grpc_gateway.GrpcService/GrpcStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcServiceGrpcStreamClient{stream}
	return x, nil
}

type GrpcService_GrpcStreamClient interface {
	Send(*comm_proto.GrpcRequest) error
	Recv() (*comm_proto.GrpcReply, error)
	grpc.ClientStream
}

type grpcServiceGrpcStreamClient struct {
	grpc.ClientStream
}

func (x *grpcServiceGrpcStreamClient) Send(m *comm_proto.GrpcRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grpcServiceGrpcStreamClient) Recv() (*comm_proto.GrpcReply, error) {
	m := new(comm_proto.GrpcReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GrpcServiceServer is the server API for GrpcService service.
type GrpcServiceServer interface {
	GrpcReq(context.Context, *comm_proto.GrpcRequest) (*comm_proto.GrpcReply, error)
	GrpcStream(GrpcService_GrpcStreamServer) error
}

func RegisterGrpcServiceServer(s *grpc.Server, srv GrpcServiceServer) {
	s.RegisterService(&_GrpcService_serviceDesc, srv)
}

func _GrpcService_GrpcReq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(comm_proto.GrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServiceServer).GrpcReq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_gateway.GrpcService/GrpcReq",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServiceServer).GrpcReq(ctx, req.(*comm_proto.GrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcService_GrpcStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcServiceServer).GrpcStream(&grpcServiceGrpcStreamServer{stream})
}

type GrpcService_GrpcStreamServer interface {
	Send(*comm_proto.GrpcReply) error
	Recv() (*comm_proto.GrpcRequest, error)
	grpc.ServerStream
}

type grpcServiceGrpcStreamServer struct {
	grpc.ServerStream
}

func (x *grpcServiceGrpcStreamServer) Send(m *comm_proto.GrpcReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grpcServiceGrpcStreamServer) Recv() (*comm_proto.GrpcRequest, error) {
	m := new(comm_proto.GrpcRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GrpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_gateway.GrpcService",
	HandlerType: (*GrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GrpcReq",
			Handler:    _GrpcService_GrpcReq_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GrpcStream",
			Handler:       _GrpcService_GrpcStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc-gateway/proto/gateway.proto",
}

func init() {
	proto.RegisterFile("grpc-gateway/proto/gateway.proto", fileDescriptor_gateway_11ec5b027450ea32)
}

var fileDescriptor_gateway_11ec5b027450ea32 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x48, 0x2f, 0x2a, 0x48,
	0xd6, 0x4d, 0x4f, 0x2c, 0x49, 0x2d, 0x4f, 0xac, 0xd4, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x87,
	0xf2, 0xf4, 0xc0, 0x3c, 0x21, 0x1e, 0x90, 0x8a, 0x78, 0xa8, 0x98, 0x94, 0x68, 0x72, 0x7e, 0x6e,
	0x6e, 0x3c, 0x54, 0x5d, 0x51, 0x41, 0x32, 0x44, 0x91, 0x51, 0x1f, 0x23, 0x17, 0xb7, 0x7b, 0x51,
	0x41, 0x72, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x35, 0x17, 0x3b, 0x88, 0x1b, 0x94,
	0x5a, 0x28, 0x24, 0xae, 0x87, 0xd0, 0xa2, 0x07, 0x15, 0x2c, 0x4d, 0x2d, 0x2e, 0x91, 0x12, 0xc5,
	0x94, 0x28, 0xc8, 0xa9, 0x54, 0x62, 0x10, 0x72, 0xe2, 0xe2, 0x02, 0x9b, 0x55, 0x52, 0x94, 0x9a,
	0x98, 0x4b, 0xba, 0x7e, 0x0d, 0x46, 0x03, 0x46, 0x27, 0xe7, 0x28, 0xc7, 0xf4, 0xcc, 0x92, 0x8c,
	0xd2, 0x24, 0x90, 0x22, 0xfd, 0x9c, 0x82, 0x4a, 0xdd, 0xbc, 0xd4, 0x7c, 0xfd, 0xdc, 0xcc, 0xe4,
	0xa2, 0x7c, 0xdd, 0xb4, 0xa2, 0xc4, 0xdc, 0xd4, 0xf2, 0xfc, 0xa2, 0x6c, 0xdd, 0x92, 0xd4, 0xe2,
	0x12, 0x7d, 0x94, 0x10, 0x40, 0xf6, 0x6c, 0x12, 0x1b, 0xd8, 0x6c, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf5, 0x9a, 0xc5, 0x34, 0x25, 0x01, 0x00, 0x00,
}
